### ISSUE TITLE
module clock

### ISSUE THREAD

**Issue by Stefane56** [sparkfun/RTC-Module#4]
bonjour a tous
j aimerais mettre en majuscule la première lettre du jour et du mois dans le module clock
impossible de trouver

merci pour votre aide

**Comment by bboyho** [comment]
Google Translation: 

    Hello everyone
    I would like to capitalize the first letter of the day and month in the clock module
    impossible to find
    
    Thanks for your help

This seems more like a technical support question than an issue related to the GitHub repository. I am not sure what library/libraries that you are using and how you are displaying the data. There are a few RTC libraries out there that use the DS1307 . If you are using the SparkFun Arduino library from the [DS1307 code repository ](https://github.com/sparkfun/SparkFun_DS1307_RTC_Arduino_Library), it should capitalize the day of the week when you make a call to [`rtc.dayStr()`](https://github.com/sparkfun/SparkFun_DS1307_RTC_Arduino_Library/blob/68f64b103d014f448c280bb24385430e1011feec/src/SparkFunDS1307RTC.h#L73). It looks like you would have to create some [`if`](https://www.arduino.cc/reference/en/language/structure/control-structure/if/) statements to print out the month. Although, you could utilize the [Arduino Time Library](https://github.com/PaulStoffregen/Time) that has code to convert the numbers to strings.

For further assistance, you man want to try checking out the forums:

* [Arduino.cc Forums](https://forum.arduino.cc/)
* [SparkFun Forums](https://forum.sparkfun.com/)
